"""FACTCHECK phase E: emit factcheck.sh.

CI steps run on a disposable runner, as a user who can install anything,
with services already provisioned. A developer's machine is none of those
things, so the commands are not replayed blindly:

  - anything not literal (${{ ... }}) is dropped, never guessed at
  - anything that publishes (npm publish, docker push, gh release) is dropped
  - anything needing a system package manager is printed for the reader to
    run, never executed -- a generated script does not get to sudo
  - services CI declares become a preflight check, and optionally the exact
    docker commands that satisfy it

Everything kept carries the file and line it came from, so the script is
auditable against the repo before it is run.
"""
import re

# Commands that only make sense inside a CI runner.
CI_ONLY = re.compile(
    # Any GITHUB_* variable: the runner defines them, a laptop does not.
    r"\$\{?GITHUB_\w+|::set-output|actions/|runner\.temp|hashFiles\("
    r"|\$\{?RUNNER_\w+", re.I)

# Commands that change the world outside this machine.
PUBLISHES = re.compile(
    r"\b(npm publish|yarn publish|pnpm publish|cargo publish|twine upload"
    r"|gh release|docker push|maturin publish|gem push|mix hex\.publish"
    r"|aws s3|gcloud|kubectl apply|terraform apply|helm upgrade)\b", re.I)

# Needs root or a system package manager: shown, never run.
NEEDS_ROOT = re.compile(
    r"^\s*sudo\b|\b(apt-get|apt|dnf|yum|apk|pacman|zypper|brew|choco)\s+"
    r"(install|add|update|upgrade)\b"
    # A global install writes outside the project and usually wants root.
    r"|\b(npm (install|i) -g|npm -g|yarn global add|pnpm add -g|gem install)\b",
    re.I)

# Destructive enough to want a human in the loop.
DESTRUCTIVE = re.compile(
    r"\brm\s+-[rf]|\bdb:drop\b|\bdropdb\b|--force\b|\bgit\s+(push|reset --hard)\b",
    re.I)

SERVICE_PORTS = {
    "postgres": 5432, "mysql": 3306, "mariadb": 3306, "redis": 6379,
    "valkey": 6379, "mongo": 27017, "clickhouse": 8123, "elasticsearch": 9200,
    "opensearch": 9200, "rabbitmq": 5672, "kafka": 9092, "memcached": 11211,
    "minio": 9000, "cassandra": 9042, "neo4j": 7687, "nats": 4222,
}

VERSION_CMD = {
    "node": "node --version", "python": "python3 --version",
    "go": "go version", "ruby": "ruby --version", "rust": "rustc --version",
    "java": "java -version 2>&1 | head -1", "php": "php --version | head -1",
    "elixir": "elixir --version | tail -1", "deno": "deno --version | head -1",
    "bun": "bun --version", "dotnet": "dotnet --version",
    "pnpm": "pnpm --version", "uv": "uv --version",
}


def classify_command(cmd):
    """keep | manual | drop, with the reason. Fixed rules, no judgement."""
    if "${{" in cmd:
        return "drop", "not literal in CI"
    if CI_ONLY.search(cmd):
        return "drop", "only meaningful inside a CI runner"
    if PUBLISHES.search(cmd):
        return "drop", "publishes outside this machine"
    if NEEDS_ROOT.search(cmd):
        return "manual", "needs root or a system package manager"
    if DESTRUCTIVE.search(cmd):
        return "manual", "destructive"
    return "keep", ""


def _port_of(service, note):
    m = re.search(r"ports (\d+):", note or "")
    if m:
        return int(m.group(1))
    return SERVICE_PORTS.get(service)


def _docker_run(res):
    """The CI service block, restated as the docker command that satisfies it.

    The credentials come from the service's own `env:` where CI declares them.
    A generic POSTGRES_PASSWORD=postgres would start a database the project
    then cannot authenticate against -- netbox's CI uses netbox/netbox.
    """
    image = str(res.value or "").split(" | ")[0]
    if not image or "(implied" in image:
        image = res.key
    port = _port_of(res.key, res.winner.note)
    bits = ["docker run -d", "--name factcheck-%s" % res.key]
    if port:
        bits.append("-p %d:%d" % (port, port))
    declared = [(k, v) for k, v in (res.winner.data.get("env") or [])
                if SHELL_IDENT.match(str(k))]
    for key, val in (declared or _service_env(res.key)):
        bits.append("-e %s=%s" % (key, _sh(val) if " " in str(val) else val))
    bits.append(image)
    return " ".join(bits)


def _service_env(kind):
    """The minimum a stock image needs to start. Not invented -- documented."""
    return {
        "postgres": [("POSTGRES_PASSWORD", "postgres")],
        "mysql": [("MYSQL_ROOT_PASSWORD", "mysql")],
        "mariadb": [("MARIADB_ROOT_PASSWORD", "mariadb")],
    }.get(kind, [])


def _sh(text):
    """Single-quote for the shell."""
    return "'" + str(text).replace("'", "'\\''") + "'"


def render_script(meta, report):
    out = []
    w = out.append
    primary = meta.get("primary")
    slug = "%s/%s" % (meta["owner"], meta["name"])

    w("#!/usr/bin/env bash")
    w("#")
    w("# %s -- setup derived from CI, not from prose." % slug)
    w("#")
    w("# Generated by FACTCHECK from %s at %s" % (slug, meta["sha"][:12]))
    if primary:
        w("# Source of every command below: %s" % primary["path"])
    w("#")
    w("# These commands were read from a CI workflow. CI runs on a disposable")
    w("# machine with root and with its services already running; your machine")
    w("# is not that. Read this before you run it -- every line cites the file")
    w("# and line it came from, so it can be checked against the repo.")
    w("#")
    w("# Dropped on purpose: anything not literal in CI, anything that")
    w("# publishes, and anything needing sudo (printed instead, never run).")
    w("#")
    w("# Run this from the root of a clone of the repository above; the")
    w("# commands are the ones CI runs there, with its paths.")
    w("#")
    w("# One limit worth knowing: commands are taken individually from CI")
    w("# steps, so any `if` around them in the original workflow is not")
    w("# reproduced here. Read the cited lines if a step looks conditional.")
    w("")
    w("set -euo pipefail")
    w("")
    w("DRY_RUN=0")
    w("START_SERVICES=0")
    w("SKIP_TESTS=0")
    w("")
    w("usage() {")
    w("  cat <<'EOF'")
    w("factcheck.sh -- reproduce this repo's CI setup locally")
    w("")
    w("  --dry-run         print every command, run nothing")
    w("  --with-services   start the services CI declares, via docker")
    w("  --skip-tests      set up only; do not run the test suite")
    w("  -h, --help        this")
    w("EOF")
    w("}")
    w("")
    w('while [ $# -gt 0 ]; do')
    w('  case "$1" in')
    w("    --dry-run) DRY_RUN=1 ;;")
    w("    --with-services) START_SERVICES=1 ;;")
    w("    --skip-tests) SKIP_TESTS=1 ;;")
    w("    -h|--help) usage; exit 0 ;;")
    w('    *) echo "unknown option: $1" >&2; usage; exit 2 ;;')
    w("  esac")
    w("  shift")
    w("done")
    w("")
    w("bold() { printf '\\n\\033[1m==> %s\\033[0m\\n' \"$1\"; }")
    w("info() { printf '    %s\\n' \"$1\"; }")
    w("warn() { printf '    \\033[33m!  %s\\033[0m\\n' \"$1\"; }")
    w("")
    w("# Run one command, citing where it came from.")
    w("step() { # step <cite> <command>")
    w('  printf "    \\033[2m%s\\033[0m\\n    $ %s\\n" "$1" "$2"')
    w('  [ "$DRY_RUN" = 1 ] && return 0')
    w('  ( eval "$2" )')
    w("}")
    w("")
    w("step_in() { # step_in <dir> <cite> <command>")
    w('  printf "    \\033[2m%s (in %s)\\033[0m\\n    $ %s\\n" "$2" "$1" "$3"')
    w('  [ "$DRY_RUN" = 1 ] && return 0')
    w('  ( cd "$1" && eval "$3" )')
    w("}")
    w("")
    w("have() { command -v \"$1\" >/dev/null 2>&1; }")
    w("")
    w("port_open() { # port_open <port>")
    w('  (exec 3<>"/dev/tcp/127.0.0.1/$1") >/dev/null 2>&1')
    w("}")
    w("")

    w('bold "Where you are"')
    w('if [ -d .git ]; then')
    w('  origin="$(git config --get remote.origin.url 2>/dev/null || true)"')
    w('  case "$origin" in')
    w('    *%s*) info "In a clone of %s." ;;' % (slug, slug))
    w('    "") warn "This git repo has no origin; check you are in %s." ;;' % slug)
    w('    *) warn "This looks like $origin, not %s. The commands below assume '
      'the latter." ;;' % slug)
    w("  esac")
    w("else")
    w('  warn "Not inside a git repository. Run this from the root of a clone '
      'of %s."' % slug)
    w("fi")
    w("")

    _preflight(w, meta, report)
    _environment(w, report)
    _services(w, report)
    _commands(w, report)

    w('bold "Done"')
    w('info "Every command above came from %s at %s."'
      % (primary["path"] if primary else "the repo", meta["sha"][:12]))
    return "\n".join(out).rstrip() + "\n"


def _preflight(w, meta, report):
    runtimes = [r for r in report.by_fact("runtime") if r.winner]
    w('bold "Checking what CI says this needs"')
    if not runtimes:
        w('info "CI pins no runtime version."')
        w("")
        return
    w("MISSING=0")
    for res in runtimes:
        cmd = VERSION_CMD.get(res.key)
        want = res.value
        if not cmd:
            w('info %s' % _sh("%s %s expected -- %s" % (res.key, want,
                                                        res.winner.cite)))
            continue
        tool = cmd.split()[0]
        w('if have %s; then' % tool)
        w('  info "%s: want %s, have $(%s)"'
          % (res.key, str(want).replace('"', ""), cmd))
        w("else")
        w('  warn "%s not installed -- CI uses %s (%s)"'
          % (res.key, str(want).replace('"', ""), res.winner.cite))
        w("  MISSING=1")
        w("fi")
    w('if [ "$MISSING" = 1 ]; then')
    w('  warn "Install what is missing before continuing."')
    w("fi")
    w("")


SHELL_VARS = {"HOME", "PATH", "PWD", "USER", "SHELL", "TMPDIR", "LANG",
              "HOSTNAME", "TERM", "UID", "EUID", "PS1", "IFS", "OLDPWD"}

# CI accepts env keys a shell cannot export: keycloak's workflows set
# `old-version`, and `export old-version=...` is a runtime syntax error that
# `bash -n` does not catch.
SHELL_IDENT = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def _environment(w, report):
    """CI env blocks, re-exported. `mix deps.get --only $MIX_ENV` is not a
    runnable command until MIX_ENV exists."""
    all_env = [r for r in report.by_fact("env")
               if r.winner and r.winner.resolved and r.value]
    rows = [r for r in all_env if SHELL_IDENT.match(str(r.key))]
    unexportable = [r for r in all_env if r not in rows]
    exported = set()
    if rows:
        w('bold "Environment CI sets"')
        for res in rows:
            exported.add(res.key)
            # Jobs may set the same variable differently. The document shows
            # every value; a script has to pick one, so it takes the winning
            # claim -- the highest-authority citation, not a joined string.
            # Collapse whitespace: a multi-line CI value exported verbatim
            # would embed a newline in the variable.
            value = " ".join(str(res.winner.value).split())
            w("export %s=%s" % (res.key, _sh(value)))
            w('info %s' % _sh("%s=%s  <- %s" % (res.key, value,
                                                res.winner.cite)))
            others = [v for v in res.values if v != value]
            if others:
                w('info %s' % _sh("  other jobs use: %s" % ", ".join(others[:4])))
        w("")

    if unexportable:
        w('bold "Set by CI but not a valid shell variable name"')
        for res in unexportable[:8]:
            w('warn %s' % _sh("%s=%s  <- %s" % (res.key, res.winner.value,
                                                res.winner.cite)))
        w("")

    referenced = set()
    for fact in ("install", "setup", "build", "test"):
        for claim, _ in _kept(report, fact):
            referenced |= set(re.findall(r"\$\{?([A-Z][A-Z0-9_]{2,})\}?",
                                         str(claim.value)))
    unknown = sorted(referenced - exported - SHELL_VARS)
    if unknown:
        w('bold "Referenced but not set by CI"')
        w('info "These appear in commands below; CI gets them from its own'
          ' environment, so set them yourself if a step fails:"')
        for name in unknown[:12]:
            w('warn %s' % _sh(name))
        w("")


def _services(w, report):
    rows = [r for r in report.by_fact("services") if r.winner]
    if not rows:
        return
    w('bold "Services CI runs alongside the tests"')
    for res in rows:
        port = _port_of(res.key, res.winner.note)
        w('info %s' % _sh("%s  %s  <- %s" % (res.key, res.value or "", res.winner.cite)))
        if not port:
            continue
        w('if port_open %d; then' % port)
        w('  info "%s: something is listening on %d"' % (res.key, port))
        w('elif [ "$START_SERVICES" = 1 ]; then')
        w('  step %s %s' % (_sh(res.winner.cite), _sh(_docker_run(res))))
        w("else")
        w('  warn "%s: nothing on port %d. Start it, or re-run with --with-services:"'
          % (res.key, port))
        w('  info %s' % _sh(_docker_run(res)))
        w("fi")
    w("")


def _commands(w, report):
    sections = [("install", "Install"), ("setup", "Setup"), ("build", "Build")]
    for fact, title in sections:
        _section(w, report, fact, title)
    rows = _kept(report, "test")
    if not rows:
        return
    w('if [ "$SKIP_TESTS" = 1 ]; then')
    w('  bold "Skipping tests (--skip-tests)"')
    w("else")
    w('  bold "Test"')
    for claim, _ in rows:
        _emit(w, claim, indent="  ")
    w("fi")
    w("")


def _section(w, report, fact, title):
    rows = _kept(report, fact)
    manual = _manual(report, fact)
    if not rows and not manual:
        return
    w('bold "%s"' % title)
    for claim, reason in manual:
        w('warn %s' % _sh("run this yourself (%s): %s" % (reason, claim.value)))
        w('info %s' % _sh(claim.cite))
    for claim, _ in rows:
        _emit(w, claim)
    w("")


def _emit(w, claim, indent=""):
    if "in a directory CI computes" in (claim.note or ""):
        # Running this in the wrong directory is worse than not running it.
        w('%swarn %s' % (indent, _sh(
            "run this yourself, in the directory CI computes: %s" % claim.value)))
        w('%sinfo %s' % (indent, _sh(claim.cite)))
        return
    wd = ""
    m = re.search(r", in (\S+)", claim.note or "")
    if m:
        wd = m.group(1)
    if wd:
        w('%sstep_in %s %s %s' % (indent, _sh(wd), _sh(claim.cite),
                                  _sh(claim.value)))
    else:
        w('%sstep %s %s' % (indent, _sh(claim.cite), _sh(claim.value)))


def _kept(report, fact):
    out = []
    for res in report.by_fact(fact):
        if not res.winner:
            continue
        for claim in res.members:
            verdict, reason = classify_command(str(claim.value))
            if verdict == "keep":
                out.append((claim, reason))
    return _dedupe(out)


def _manual(report, fact):
    out = []
    for res in report.by_fact(fact):
        if not res.winner:
            continue
        for claim in res.members:
            verdict, reason = classify_command(str(claim.value))
            if verdict == "manual":
                out.append((claim, reason))
    return _dedupe(out)


def _dedupe(rows):
    seen, out = set(), []
    for claim, reason in rows:
        key = " ".join(str(claim.value).split())
        if key not in seen:
            seen.add(key)
            out.append((claim, reason))
    return out
