#!/usr/bin/env bash
#
# plausible/analytics -- setup derived from CI, not from prose.
#
# Generated by FACTCHECK from plausible/analytics at 543b30185c10
# Source of every command below: .github/workflows/elixir.yml
#
# These commands were read from a CI workflow. CI runs on a disposable
# machine with root and with its services already running; your machine
# is not that. Read this before you run it -- every line cites the file
# and line it came from, so it can be checked against the repo.
#
# Dropped on purpose: anything not literal in CI, anything that
# publishes, and anything needing sudo (printed instead, never run).
#
# Run this from the root of a clone of the repository above; the
# commands are the ones CI runs there, with its paths.
#
# One limit worth knowing: commands are taken individually from CI
# steps, so any `if` around them in the original workflow is not
# reproduced here. Read the cited lines if a step looks conditional.

set -euo pipefail

DRY_RUN=0
START_SERVICES=0
SKIP_TESTS=0

usage() {
  cat <<'EOF'
factcheck.sh -- reproduce this repo's CI setup locally

  --dry-run         print every command, run nothing
  --with-services   start the services CI declares, via docker
  --skip-tests      set up only; do not run the test suite
  -h, --help        this
EOF
}

while [ $# -gt 0 ]; do
  case "$1" in
    --dry-run) DRY_RUN=1 ;;
    --with-services) START_SERVICES=1 ;;
    --skip-tests) SKIP_TESTS=1 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "unknown option: $1" >&2; usage; exit 2 ;;
  esac
  shift
done

bold() { printf '\n\033[1m==> %s\033[0m\n' "$1"; }
info() { printf '    %s\n' "$1"; }
warn() { printf '    \033[33m!  %s\033[0m\n' "$1"; }

# Run one command, citing where it came from.
step() { # step <cite> <command>
  printf "    \033[2m%s\033[0m\n    $ %s\n" "$1" "$2"
  [ "$DRY_RUN" = 1 ] && return 0
  ( eval "$2" )
}

step_in() { # step_in <dir> <cite> <command>
  printf "    \033[2m%s (in %s)\033[0m\n    $ %s\n" "$2" "$1" "$3"
  [ "$DRY_RUN" = 1 ] && return 0
  ( cd "$1" && eval "$3" )
}

have() { command -v "$1" >/dev/null 2>&1; }

port_open() { # port_open <port>
  (exec 3<>"/dev/tcp/127.0.0.1/$1") >/dev/null 2>&1
}

bold "Where you are"
if [ -d .git ]; then
  origin="$(git config --get remote.origin.url 2>/dev/null || true)"
  case "$origin" in
    *plausible/analytics*) info "In a clone of plausible/analytics." ;;
    "") warn "This git repo has no origin; check you are in plausible/analytics." ;;
    *) warn "This looks like $origin, not plausible/analytics. The commands below assume the latter." ;;
  esac
else
  warn "Not inside a git repository. Run this from the root of a clone of plausible/analytics."
fi

bold "Checking what CI says this needs"
MISSING=0
if have elixir; then
  info "elixir: want 1.20.4-otp-28, have $(elixir --version | tail -1)"
else
  warn "elixir not installed -- CI uses 1.20.4-otp-28 (.tool-versions:2)"
  MISSING=1
fi
info 'erlang 28.5.0.5 expected -- .tool-versions:1'
if have node; then
  info "node: want 24.17.0, have $(node --version)"
else
  warn "node not installed -- CI uses 24.17.0 (.tool-versions:3)"
  MISSING=1
fi
if [ "$MISSING" = 1 ]; then
  warn "Install what is missing before continuing."
fi

bold "Environment CI sets"
export BASE_URL='http://localhost:8111'
info 'BASE_URL=http://localhost:8111  <- .github/workflows/elixir.yml:124'
export MINIO_HOST_FOR_CLICKHOUSE='172.17.0.1'
info 'MINIO_HOST_FOR_CLICKHOUSE=172.17.0.1  <- .github/workflows/elixir.yml:109'
export MIX_ENV='e2e_test'
info 'MIX_ENV=e2e_test  <- .github/workflows/elixir.yml:123'
info '  other jobs use: test'

bold "Services CI runs alongside the tests"
info 'clickhouse  clickhouse/clickhouse-server:25.11.5.8-alpine  <- .github/workflows/elixir.yml:42'
if port_open 8123; then
  info "clickhouse: something is listening on 8123"
elif [ "$START_SERVICES" = 1 ]; then
  if ! step '.github/workflows/elixir.yml:42' 'docker run -d --name factcheck-clickhouse -p 8123:8123 -e CLICKHOUSE_SKIP_USER_SETUP=1 clickhouse/clickhouse-server:25.11.5.8-alpine'; then
    warn "could not start clickhouse. Start it yourself on port 8123 and re-run, or drop --with-services."
    exit 1
  fi
else
  warn "clickhouse: nothing on port 8123. Start it, or re-run with --with-services:"
  info 'docker run -d --name factcheck-clickhouse -p 8123:8123 -e CLICKHOUSE_SKIP_USER_SETUP=1 clickhouse/clickhouse-server:25.11.5.8-alpine'
fi
info 'postgres  postgres:18  <- .github/workflows/elixir.yml:127'
if port_open 5432; then
  info "postgres: something is listening on 5432"
elif [ "$START_SERVICES" = 1 ]; then
  if ! step '.github/workflows/elixir.yml:127' 'docker run -d --name factcheck-postgres -p 5432:5432 -e POSTGRES_PASSWORD=postgres postgres:18'; then
    warn "could not start postgres. Start it yourself on port 5432 and re-run, or drop --with-services."
    exit 1
  fi
else
  warn "postgres: nothing on port 5432. Start it, or re-run with --with-services:"
  info 'docker run -d --name factcheck-postgres -p 5432:5432 -e POSTGRES_PASSWORD=postgres postgres:18'
fi

bold "Install"
step '.github/workflows/elixir.yml:94' 'npm install --prefix ./tracker'
step '.github/workflows/elixir.yml:99' 'mix deps.get --only $MIX_ENV'
step '.github/workflows/elixir.yml:207' 'npm install --prefix ./assets'
step '.github/workflows/elixir.yml:294' 'mix deps.get'

bold "Setup"
step '.github/workflows/elixir.yml:101' 'mix do ecto.create, ecto.migrate'
step '.github/workflows/elixir.yml:208' 'mix assets.deploy'

bold "Build"
step '.github/workflows/elixir.yml:100' 'mix compile --warnings-as-errors --all-warnings'
step '.github/workflows/elixir.yml:104' 'make minio'

if [ "$SKIP_TESTS" = 1 ]; then
  bold "Skipping tests (--skip-tests)"
else
  bold "Test"
  step '.github/workflows/elixir.yml:106' 'mix test --include slow --include minio --include migrations --max-failures 1 --warnings-as-errors --partitions 6'
  step '.github/workflows/elixir.yml:113' 'mix test --include slow --include migrations --max-failures 1 --warnings-as-errors --partitions 6'
  step_in './e2e' '.github/workflows/elixir.yml:225' 'npx playwright install --with-deps chromium'
  step_in './e2e' '.github/workflows/elixir.yml:262' 'npx playwright merge-reports --reporter list ../all-e2e-blob-reports'
fi

bold "Done"
info "Every command above came from .github/workflows/elixir.yml at 543b30185c10."
