#!/usr/bin/env bash
#
# calcom/cal.com -- setup derived from CI, not from prose.
#
# Generated by FACTCHECK from calcom/cal.com at abffde336e74
# Source of every command below: .github/workflows/all-checks.yml
#
# These commands were read from a CI workflow. CI runs on a disposable
# machine with root and with its services already running; your machine
# is not that. Read this before you run it -- every line cites the file
# and line it came from, so it can be checked against the repo.
#
# Dropped on purpose: anything not literal in CI, anything that
# publishes, and anything needing sudo (printed instead, never run).
#
# One limit worth knowing: commands are taken individually from CI
# steps, so any `if` around them in the original workflow is not
# reproduced here. Read the cited lines if a step looks conditional.

set -euo pipefail

DRY_RUN=0
START_SERVICES=0
SKIP_TESTS=0

usage() {
  cat <<'EOF'
factcheck.sh -- reproduce this repo's CI setup locally

  --dry-run         print every command, run nothing
  --with-services   start the services CI declares, via docker
  --skip-tests      set up only; do not run the test suite
  -h, --help        this
EOF
}

while [ $# -gt 0 ]; do
  case "$1" in
    --dry-run) DRY_RUN=1 ;;
    --with-services) START_SERVICES=1 ;;
    --skip-tests) SKIP_TESTS=1 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "unknown option: $1" >&2; usage; exit 2 ;;
  esac
  shift
done

bold() { printf '\n\033[1m==> %s\033[0m\n' "$1"; }
info() { printf '    %s\n' "$1"; }
warn() { printf '    \033[33m!  %s\033[0m\n' "$1"; }

# Run one command, citing where it came from.
step() { # step <cite> <command>
  printf "    \033[2m%s\033[0m\n    $ %s\n" "$1" "$2"
  [ "$DRY_RUN" = 1 ] && return 0
  ( eval "$2" )
}

step_in() { # step_in <dir> <cite> <command>
  printf "    \033[2m%s (in %s)\033[0m\n    $ %s\n" "$2" "$1" "$3"
  [ "$DRY_RUN" = 1 ] && return 0
  ( cd "$1" && eval "$3" )
}

have() { command -v "$1" >/dev/null 2>&1; }

port_open() { # port_open <port>
  (exec 3<>"/dev/tcp/127.0.0.1/$1") >/dev/null 2>&1
}

bold "Checking what CI says this needs"
MISSING=0
if have node; then
  info "node: want 20, have $(node --version)"
else
  warn "node not installed -- CI uses 20 (.github/workflows/i18n.yml:31)"
  MISSING=1
fi
info 'npm >=7.0.0 expected -- package.json:222'
info 'yarn >=4.12.0 | 4.12.0 expected -- package.json:223'
if [ "$MISSING" = 1 ]; then
  warn "Install what is missing before continuing."
fi

bold "Environment CI sets"
export ALLOWED_HOSTNAMES=''\''"cal.local:3000","localhost:3000"'\'''
info 'ALLOWED_HOSTNAMES='\''"cal.local:3000","localhost:3000"'\''  <- .env.example:48'
export API_KEY_PREFIX='cal_'
info 'API_KEY_PREFIX=cal_  <- .env.example:215'
export CALCOM_APP_CREDENTIAL_ENCRYPTION_KEY='""'
info 'CALCOM_APP_CREDENTIAL_ENCRYPTION_KEY=""  <- .env.example:355'
export CALCOM_CREDENTIAL_SYNC_ENDPOINT='""'
info 'CALCOM_CREDENTIAL_SYNC_ENDPOINT=""  <- .env.example:351'
export CALCOM_CREDENTIAL_SYNC_HEADER_NAME='"calcom-credential-sync-secret"'
info 'CALCOM_CREDENTIAL_SYNC_HEADER_NAME="calcom-credential-sync-secret"  <- .env.example:349'
export CALCOM_CREDENTIAL_SYNC_SECRET='""'
info 'CALCOM_CREDENTIAL_SYNC_SECRET=""  <- .env.example:347'
export CAL_AI_CALL_RATE_PER_MINUTE='0.29'
info 'CAL_AI_CALL_RATE_PER_MINUTE=0.29  <- .env.example:385'
export CRON_API_KEY=''\''0cc0e6c35519bba620c9360cfe3e68d0'\'''
info 'CRON_API_KEY='\''0cc0e6c35519bba620c9360cfe3e68d0'\''  <- .env.example:67'
export CRON_ENABLE_APP_SYNC='false'
info 'CRON_ENABLE_APP_SYNC=false  <- .env.example:71'
export DATABASE_DIRECT_URL='"postgresql://postgres:@localhost:5450/calendso"'
info 'DATABASE_DIRECT_URL="postgresql://postgres:@localhost:5450/calendso"  <- .env.example:20'
export DATABASE_URL='"postgresql://postgres:@localhost:5450/calendso"'
info 'DATABASE_URL="postgresql://postgres:@localhost:5450/calendso"  <- .env.example:17'
export E2E_TEST_APPLE_CALENDAR_EMAIL='""'
info 'E2E_TEST_APPLE_CALENDAR_EMAIL=""  <- .env.example:332'
export E2E_TEST_APPLE_CALENDAR_PASSWORD='""'
info 'E2E_TEST_APPLE_CALENDAR_PASSWORD=""  <- .env.example:333'
export E2E_TEST_CALCOM_QA_EMAIL='"qa@example.com"'
info 'E2E_TEST_CALCOM_QA_EMAIL="qa@example.com"  <- .env.example:337'
export E2E_TEST_CALCOM_QA_PASSWORD='"password"'
info 'E2E_TEST_CALCOM_QA_PASSWORD="password"  <- .env.example:339'
export EMAIL_FROM=''\''notifications@yourselfhostedcal.com'\'''
info 'EMAIL_FROM='\''notifications@yourselfhostedcal.com'\''  <- .env.example:222'
export EMAIL_FROM_NAME=''\''Cal.diy'\'''
info 'EMAIL_FROM_NAME='\''Cal.diy'\''  <- .env.example:223'
export EMAIL_SERVER_HOST=''\''localhost'\'''
info 'EMAIL_SERVER_HOST='\''localhost'\''  <- .env.example:227'
export EMAIL_SERVER_PORT='1025'
info 'EMAIL_SERVER_PORT=1025  <- .env.example:228'
export ENABLE_ASYNC_TASKER='"false" # set to "true" to enable'
info 'ENABLE_ASYNC_TASKER="false" # set to "true" to enable  <- .env.example:477'
export GOOGLE_ADS_ENABLED='1      # To enable Google Ads tracking (gclid)'
info 'GOOGLE_ADS_ENABLED=1      # To enable Google Ads tracking (gclid)  <- .env.example:482'
export GOOGLE_LOGIN_ENABLED='false'
info 'GOOGLE_LOGIN_ENABLED=false  <- .env.example:134'
export LINKEDIN_ADS_ENABLED='1    # To enable LinkedIn Ads tracking (li_fat_id)'
info 'LINKEDIN_ADS_ENABLED=1    # To enable LinkedIn Ads tracking (li_fat_id)  <- .env.example:483'
export NEXTAUTH_URL=''\''http://localhost:3000'\'''
info 'NEXTAUTH_URL='\''http://localhost:3000'\''  <- .env.example:56'
export NEXT_PUBLIC_API_V2_URL='"http://localhost:5555/api/v2"'
info 'NEXT_PUBLIC_API_V2_URL="http://localhost:5555/api/v2"  <- .env.example:360'
export NEXT_PUBLIC_APP_NAME='"Cal.diy"'
info 'NEXT_PUBLIC_APP_NAME="Cal.diy"  <- .env.example:275'
export NEXT_PUBLIC_BOOKER_NUMBER_OF_DAYS_TO_LOAD='0 # Override the booker to only load X number of days worth of data'
info 'NEXT_PUBLIC_BOOKER_NUMBER_OF_DAYS_TO_LOAD=0 # Override the booker to only load X number of days worth of data  <- .env.example:290'
export NEXT_PUBLIC_COMPANY_NAME='"Cal.com, Inc."'
info 'NEXT_PUBLIC_COMPANY_NAME="Cal.com, Inc."  <- .env.example:277'
export NEXT_PUBLIC_EMBED_LIB_URL=''\''http://localhost:3000/embed/embed.js'\'''
info 'NEXT_PUBLIC_EMBED_LIB_URL='\''http://localhost:3000/embed/embed.js'\''  <- .env.example:31'
export NEXT_PUBLIC_FORMBRICKS_HOST_URL='https://app.formbricks.com'
info 'NEXT_PUBLIC_FORMBRICKS_HOST_URL=https://app.formbricks.com  <- .env.example:175'
export NEXT_PUBLIC_INVALIDATE_AVAILABLE_SLOTS_ON_BOOKING_FORM='0'
info 'NEXT_PUBLIC_INVALIDATE_AVAILABLE_SLOTS_ON_BOOKING_FORM=0  <- .env.example:443'
export NEXT_PUBLIC_IS_PREMIUM_NEW_PLAN='0'
info 'NEXT_PUBLIC_IS_PREMIUM_NEW_PLAN=0  <- .env.example:195'
export NEXT_PUBLIC_MINUTES_TO_BOOK='5               # Minutes'
info 'NEXT_PUBLIC_MINUTES_TO_BOOK=5               # Minutes  <- .env.example:289'
export NEXT_PUBLIC_ORGANIZATIONS_MIN_SELF_SERVE_SEATS='30'
info 'NEXT_PUBLIC_ORGANIZATIONS_MIN_SELF_SERVE_SEATS=30  <- .env.example:303'
export NEXT_PUBLIC_ORGANIZATIONS_SELF_SERVE_PRICE_NEW='37 # $37.00 per seat'
info 'NEXT_PUBLIC_ORGANIZATIONS_SELF_SERVE_PRICE_NEW=37 # $37.00 per seat  <- .env.example:304'
export NEXT_PUBLIC_QUICK_AVAILABILITY_ROLLOUT='10'
info 'NEXT_PUBLIC_QUICK_AVAILABILITY_ROLLOUT=10  <- .env.example:445'
export NEXT_PUBLIC_SUPPORT_MAIL_ADDRESS='"help@cal.diy"'
info 'NEXT_PUBLIC_SUPPORT_MAIL_ADDRESS="help@cal.diy"  <- .env.example:276'
export NEXT_PUBLIC_WEBAPP_URL=''\''http://localhost:3000'\'''
info 'NEXT_PUBLIC_WEBAPP_URL='\''http://localhost:3000'\''  <- .env.example:28'
export NEXT_PUBLIC_WEBSITE_URL=''\''http://localhost:3000'\'''
info 'NEXT_PUBLIC_WEBSITE_URL='\''http://localhost:3000'\''  <- .env.example:30'
export OUTLOOK_LOGIN_ENABLED='false'
info 'OUTLOOK_LOGIN_ENABLED=false  <- .env.example:118'
export RESERVED_SUBDOMAINS=''\''"app","auth","docs","design","console","go","status","api","saml","www","matrix","developer","cal","my","team","support","security","blog","learn","admin"'\'''
info 'RESERVED_SUBDOMAINS='\''"app","auth","docs","design","console","go","status","api","saml","www","matrix","developer","cal","my","team","support","security","blog","learn","admin"'\''  <- .env.example:50'
export RETELL_AI_TEST_MODE='false'
info 'RETELL_AI_TEST_MODE=false  <- .env.example:376'
export SALESFORCE_GRAPHQL_DELAY_MS='500'
info 'SALESFORCE_GRAPHQL_DELAY_MS=500  <- .env.example:461'
export SALESFORCE_GRAPHQL_MAX_DELAY_MS='2000'
info 'SALESFORCE_GRAPHQL_MAX_DELAY_MS=2000  <- .env.example:462'
export SALESFORCE_GRAPHQL_MAX_RETRIES='3'
info 'SALESFORCE_GRAPHQL_MAX_RETRIES=3  <- .env.example:463'
export TASKER_ENABLE_EMAILS='0'
info 'TASKER_ENABLE_EMAILS=0  <- .env.example:364'
export TASKER_ENABLE_WEBHOOKS='0'
info 'TASKER_ENABLE_WEBHOOKS=0  <- .env.example:363'
export TRIGGER_API_URL='https://api.trigger.dev'
info 'TRIGGER_API_URL=https://api.trigger.dev  <- .env.example:479'
export TZ='UTC'
info 'TZ=UTC  <- .env.example:466'

bold "Services CI runs alongside the tests"
info 'postgres  postgres  <- docker-compose.yml:15'
if port_open 5432; then
  info "postgres: something is listening on 5432"
elif [ "$START_SERVICES" = 1 ]; then
  step 'docker-compose.yml:15' 'docker run -d --name factcheck-postgres -p 5432:5432 -e POSTGRES_PASSWORD=postgres postgres'
else
  warn "postgres: nothing on port 5432. Start it, or re-run with --with-services:"
  info 'docker run -d --name factcheck-postgres -p 5432:5432 -e POSTGRES_PASSWORD=postgres postgres'
fi
info 'redis  redis:latest  <- docker-compose.yml:28'
if port_open 6379; then
  info "redis: something is listening on 6379"
elif [ "$START_SERVICES" = 1 ]; then
  step 'docker-compose.yml:28' 'docker run -d --name factcheck-redis -p 6379:6379 redis:latest'
else
  warn "redis: nothing on port 6379. Start it, or re-run with --with-services:"
  info 'docker run -d --name factcheck-redis -p 6379:6379 redis:latest'
fi

bold "Install"
warn 'run this yourself (needs root or a system package manager): npm install -g npm@11.5.1'
info '.github/workflows/changesets.yml:33'

bold "Setup"
step 'README.md:230' 'yarn workspace @calcom/prisma db-migrate'
step 'README.md:284' 'yarn db-seed'
step 'README.md:689' 'yarn seed-app-store'

bold "Build"
step 'package.json:30' 'npm run build'
step 'package.json:31' 'npm run build:ai'

if [ "$SKIP_TESTS" = 1 ]; then
  bold "Skipping tests (--skip-tests)"
else
  bold "Test"
  step 'package.json:67' 'npm run tdd'
  step 'package.json:68' 'npm run e2e'
  step 'package.json:69' 'npm run e2e:app-store'
  step 'package.json:70' 'npm run e2e:embed'
  step 'package.json:71' 'npm run e2e:embed-react'
  step 'package.json:76' 'npm run test-playwright'
  step 'package.json:77' 'npm run test'
  step 'package.json:78' 'npm run test:ui'
fi

bold "Done"
info "Every command above came from .github/workflows/all-checks.yml at abffde336e74."
