#!/usr/bin/env bash
#
# discourse/discourse -- setup derived from CI, not from prose.
#
# Generated by FACTCHECK from discourse/discourse at 5e9779d4cd41
# Source of every command below: .github/workflows/tests.yml
#
# These commands were read from a CI workflow. CI runs on a disposable
# machine with root and with its services already running; your machine
# is not that. Read this before you run it -- every line cites the file
# and line it came from, so it can be checked against the repo.
#
# Dropped on purpose: anything not literal in CI, anything that
# publishes, and anything needing sudo (printed instead, never run).
#
# Run this from the root of a clone of the repository above; the
# commands are the ones CI runs there, with its paths.
#
# One limit worth knowing: commands are taken individually from CI
# steps, so any `if` around them in the original workflow is not
# reproduced here. Read the cited lines if a step looks conditional.

set -euo pipefail

DRY_RUN=0
START_SERVICES=0
SKIP_TESTS=0

usage() {
  cat <<'EOF'
factcheck.sh -- reproduce this repo's CI setup locally

  --dry-run         print every command, run nothing
  --with-services   start the services CI declares, via docker
  --skip-tests      set up only; do not run the test suite
  -h, --help        this
EOF
}

while [ $# -gt 0 ]; do
  case "$1" in
    --dry-run) DRY_RUN=1 ;;
    --with-services) START_SERVICES=1 ;;
    --skip-tests) SKIP_TESTS=1 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "unknown option: $1" >&2; usage; exit 2 ;;
  esac
  shift
done

bold() { printf '\n\033[1m==> %s\033[0m\n' "$1"; }
info() { printf '    %s\n' "$1"; }
warn() { printf '    \033[33m!  %s\033[0m\n' "$1"; }

# Run one command, citing where it came from.
step() { # step <cite> <command>
  printf "    \033[2m%s\033[0m\n    $ %s\n" "$1" "$2"
  [ "$DRY_RUN" = 1 ] && return 0
  ( eval "$2" )
}

step_in() { # step_in <dir> <cite> <command>
  printf "    \033[2m%s (in %s)\033[0m\n    $ %s\n" "$2" "$1" "$3"
  [ "$DRY_RUN" = 1 ] && return 0
  ( cd "$1" && eval "$3" )
}

have() { command -v "$1" >/dev/null 2>&1; }

port_open() { # port_open <port>
  (exec 3<>"/dev/tcp/127.0.0.1/$1") >/dev/null 2>&1
}

bold "Where you are"
if [ -d .git ]; then
  origin="$(git config --get remote.origin.url 2>/dev/null || true)"
  case "$origin" in
    *discourse/discourse*) info "In a clone of discourse/discourse." ;;
    "") warn "This git repo has no origin; check you are in discourse/discourse." ;;
    *) warn "This looks like $origin, not discourse/discourse. The commands below assume the latter." ;;
  esac
else
  warn "Not inside a git repository. Run this from the root of a clone of discourse/discourse."
fi

bold "System packages CI's runner already had"
info "These are not installed by pip or npm. Install them yourself; this script will not run anything as root."
warn 'pg needs pg_config, from the PostgreSQL client library  <- Gemfile:93'
if command -v apt-get >/dev/null 2>&1; then
  info 'sudo apt-get install -y libpq-dev'
elif command -v brew >/dev/null 2>&1; then
  info 'brew install libpq'
elif command -v pacman >/dev/null 2>&1; then
  info 'sudo pacman -S --needed postgresql-libs'
elif command -v dnf >/dev/null 2>&1; then
  info 'sudo dnf install -y libpq-devel'
fi
warn 'mysql2 needs the MySQL client headers  <- Gemfile:241'
if command -v apt-get >/dev/null 2>&1; then
  info 'sudo apt-get install -y libmysqlclient-dev'
elif command -v brew >/dev/null 2>&1; then
  info 'brew install mysql-client'
elif command -v pacman >/dev/null 2>&1; then
  info 'sudo pacman -S --needed mariadb-libs'
elif command -v dnf >/dev/null 2>&1; then
  info 'sudo dnf install -y mysql-devel'
fi

bold "Checking what CI says this needs"
MISSING=0
if have node; then
  info "node: want 24, have $(node --version)"
else
  warn "node not installed -- CI uses 24 (.github/workflows/developer-docs-lint.yml:41)"
  MISSING=1
fi
if have pnpm; then
  info "pnpm: want ^10 | 10.34.5, have $(pnpm --version)"
else
  warn "pnpm not installed -- CI uses ^10 | 10.34.5 (package.json:52)"
  MISSING=1
fi
if have ruby; then
  info "ruby: want 3.3, have $(ruby --version)"
else
  warn "ruby not installed -- CI uses 3.3 (.github/workflows/developer-docs-publish.yml:37)"
  MISSING=1
fi
if [ "$MISSING" = 1 ]; then
  warn "Install what is missing before continuing."
fi

bold "Environment CI sets"
export CAPYBARA_DEFAULT_MAX_WAIT_TIME='20'
info 'CAPYBARA_DEFAULT_MAX_WAIT_TIME=20  <- .github/workflows/tests.yml:54'
export CHEAP_SOURCE_MAPS='1'
info 'CHEAP_SOURCE_MAPS=1  <- .github/workflows/tests.yml:57'
export CHECKOUT_TIMEOUT='10'
info 'CHECKOUT_TIMEOUT=10  <- .github/workflows/tests.yml:308'
export DBUS_SESSION_BUS_ADDRESS='unix:path=/dev/null'
info 'DBUS_SESSION_BUS_ADDRESS=unix:path=/dev/null  <- .github/workflows/tests.yml:58'
export EMBER_ENV='development'
info 'EMBER_ENV=development  <- .github/workflows/tests.yml:60'
export MINIO_RUNNER_INSTALL_DIR='/home/discourse/.minio_runner'
info 'MINIO_RUNNER_INSTALL_DIR=/home/discourse/.minio_runner  <- .github/workflows/tests.yml:59'
export MINIO_RUNNER_LOG_LEVEL='WARN'
info 'MINIO_RUNNER_LOG_LEVEL=WARN  <- .github/workflows/tests.yml:55'
export PGPASSWORD='discourse'
info 'PGPASSWORD=discourse  <- .github/workflows/tests.yml:52'
export PGUSER='discourse'
info 'PGUSER=discourse  <- .github/workflows/tests.yml:51'
export PLAYWRIGHT_BROWSERS_PATH='/home/discourse/.cache/ms-playwright'
info 'PLAYWRIGHT_BROWSERS_PATH=/home/discourse/.cache/ms-playwright  <- .github/workflows/tests.yml:63'
export QUNIT_REUSE_BUILD='1'
info 'QUNIT_REUSE_BUILD=1  <- .github/workflows/tests.yml:62'
export RAILS_ENV='test'
info 'RAILS_ENV=test  <- .github/workflows/tests.yml:50'
export TEMPORARY_DB_PORT='11000'
info 'TEMPORARY_DB_PORT=11000  <- .github/workflows/tests.yml:193'
info '  other jobs use: 11001'

bold "Install"
step '.github/workflows/tests.yml:133' 'bundle install --jobs $(($(nproc) - 1))'
step '.github/workflows/tests.yml:140' 'pnpm install --frozen-lockfile'

bold "Setup"
step '.github/workflows/tests.yml:179' 'bin/rake db:create'
step '.github/workflows/tests.yml:183' 'bin/rake db:migrate'
step '.github/workflows/tests.yml:187' 'bin/rake parallel:create parallel:migrate'

if [ "$SKIP_TESTS" = 1 ]; then
  bold "Skipping tests (--skip-tests)"
else
  bold "Test"
  step_in 'frontend/asset-processor' '.github/workflows/tests.yml:280' 'pnpm test'
  step '.github/workflows/tests.yml:303' 'pnpm playwright-install'
fi

bold "Done"
info "Every command above came from .github/workflows/tests.yml at 5e9779d4cd41."
