#!/usr/bin/env bash
#
# expressjs/express -- setup derived from CI, not from prose.
#
# Generated by FACTCHECK from expressjs/express at 023767fe9872
# Source of every command below: .github/workflows/ci.yml
#
# These commands were read from a CI workflow. CI runs on a disposable
# machine with root and with its services already running; your machine
# is not that. Read this before you run it -- every line cites the file
# and line it came from, so it can be checked against the repo.
#
# Dropped on purpose: anything not literal in CI, anything that
# publishes, and anything needing sudo (printed instead, never run).
#
# Run this from the root of a clone of the repository above; the
# commands are the ones CI runs there, with its paths.
#
# One limit worth knowing: commands are taken individually from CI
# steps, so any `if` around them in the original workflow is not
# reproduced here. Read the cited lines if a step looks conditional.

set -euo pipefail

DRY_RUN=0
START_SERVICES=0
SKIP_TESTS=0

usage() {
  cat <<'EOF'
factcheck.sh -- reproduce this repo's CI setup locally

  --dry-run         print every command, run nothing
  --with-services   start the services CI declares, via docker
  --skip-tests      set up only; do not run the test suite
  -h, --help        this
EOF
}

while [ $# -gt 0 ]; do
  case "$1" in
    --dry-run) DRY_RUN=1 ;;
    --with-services) START_SERVICES=1 ;;
    --skip-tests) SKIP_TESTS=1 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "unknown option: $1" >&2; usage; exit 2 ;;
  esac
  shift
done

bold() { printf '\n\033[1m==> %s\033[0m\n' "$1"; }
info() { printf '    %s\n' "$1"; }
warn() { printf '    \033[33m!  %s\033[0m\n' "$1"; }

# Run one command, citing where it came from.
step() { # step <cite> <command>
  printf "    \033[2m%s\033[0m\n    $ %s\n" "$1" "$2"
  [ "$DRY_RUN" = 1 ] && return 0
  ( eval "$2" )
}

step_in() { # step_in <dir> <cite> <command>
  printf "    \033[2m%s (in %s)\033[0m\n    $ %s\n" "$2" "$1" "$3"
  [ "$DRY_RUN" = 1 ] && return 0
  ( cd "$1" && eval "$3" )
}

have() { command -v "$1" >/dev/null 2>&1; }

port_open() { # port_open <port>
  (exec 3<>"/dev/tcp/127.0.0.1/$1") >/dev/null 2>&1
}

bold "Where you are"
if [ -d .git ]; then
  origin="$(git config --get remote.origin.url 2>/dev/null || true)"
  case "$origin" in
    *expressjs/express*) info "In a clone of expressjs/express." ;;
    "") warn "This git repo has no origin; check you are in expressjs/express." ;;
    *) warn "This looks like $origin, not expressjs/express. The commands below assume the latter." ;;
  esac
else
  warn "Not inside a git repository. Run this from the root of a clone of expressjs/express."
fi

bold "Checking what CI says this needs"
MISSING=0
if have node; then
  info "node: want 18 | 19 | 20 | 21 | 22 | 23 | 24 | 25 | 26, have $(node --version)"
else
  warn "node not installed -- CI uses 18 | 19 | 20 | 21 | 22 | 23 | 24 | 25 | 26 (.github/workflows/ci.yml:63)"
  MISSING=1
fi
if [ "$MISSING" = 1 ]; then
  warn "Install what is missing before continuing."
fi

bold "Install"
step '.github/workflows/ci.yml:39' 'npm install --ignore-scripts --include=dev'
step '.github/workflows/ci.yml:71' 'npm install'

if [ "$SKIP_TESTS" = 1 ]; then
  bold "Skipping tests (--skip-tests)"
else
  bold "Test"
  step '.github/workflows/ci.yml:80' 'npm run test-ci'
fi

bold "Done"
info "Every command above came from .github/workflows/ci.yml at 023767fe9872."
