#!/usr/bin/env bash
#
# ggml-org/llama.cpp -- setup derived from CI, not from prose.
#
# Generated by FACTCHECK from ggml-org/llama.cpp at 74a7c897f049
# Source of every command below: .github/workflows/build-cpu.yml
#
# These commands were read from a CI workflow. CI runs on a disposable
# machine with root and with its services already running; your machine
# is not that. Read this before you run it -- every line cites the file
# and line it came from, so it can be checked against the repo.
#
# Dropped on purpose: anything not literal in CI, anything that
# publishes, and anything needing sudo (printed instead, never run).
#
# One limit worth knowing: commands are taken individually from CI
# steps, so any `if` around them in the original workflow is not
# reproduced here. Read the cited lines if a step looks conditional.

set -euo pipefail

DRY_RUN=0
START_SERVICES=0
SKIP_TESTS=0

usage() {
  cat <<'EOF'
factcheck.sh -- reproduce this repo's CI setup locally

  --dry-run         print every command, run nothing
  --with-services   start the services CI declares, via docker
  --skip-tests      set up only; do not run the test suite
  -h, --help        this
EOF
}

while [ $# -gt 0 ]; do
  case "$1" in
    --dry-run) DRY_RUN=1 ;;
    --with-services) START_SERVICES=1 ;;
    --skip-tests) SKIP_TESTS=1 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "unknown option: $1" >&2; usage; exit 2 ;;
  esac
  shift
done

bold() { printf '\n\033[1m==> %s\033[0m\n' "$1"; }
info() { printf '    %s\n' "$1"; }
warn() { printf '    \033[33m!  %s\033[0m\n' "$1"; }

# Run one command, citing where it came from.
step() { # step <cite> <command>
  printf "    \033[2m%s\033[0m\n    $ %s\n" "$1" "$2"
  [ "$DRY_RUN" = 1 ] && return 0
  ( eval "$2" )
}

step_in() { # step_in <dir> <cite> <command>
  printf "    \033[2m%s (in %s)\033[0m\n    $ %s\n" "$2" "$1" "$3"
  [ "$DRY_RUN" = 1 ] && return 0
  ( cd "$1" && eval "$3" )
}

have() { command -v "$1" >/dev/null 2>&1; }

port_open() { # port_open <port>
  (exec 3<>"/dev/tcp/127.0.0.1/$1") >/dev/null 2>&1
}

bold "Checking what CI says this needs"
MISSING=0
if have java; then
  info "java: want 17, have $(java -version 2>&1 | head -1)"
else
  warn "java not installed -- CI uses 17 (.github/workflows/build-android.yml:48)"
  MISSING=1
fi
if have node; then
  info "node: want 24, have $(node --version)"
else
  warn "node not installed -- CI uses 24 (.github/workflows/ui.yml:59)"
  MISSING=1
fi
if have python3; then
  info "python: want 3.11, have $(python3 --version)"
else
  warn "python not installed -- CI uses 3.11 (.github/workflows/pre-tokenizer-hashes.yml:24)"
  MISSING=1
fi
if [ "$MISSING" = 1 ]; then
  warn "Install what is missing before continuing."
fi

bold "Environment CI sets"
export OPENBLAS_VERSION='0.3.23'
info 'OPENBLAS_VERSION=0.3.23  <- .github/workflows/build-cpu.yml:145'
export SDE_VERSION='9.33.0-2024-01-07'
info 'SDE_VERSION=9.33.0-2024-01-07  <- .github/workflows/build-cpu.yml:146'

bold "Install"
warn 'run this yourself (needs root or a system package manager): sudo apt-get install -y --no-install-recommends'
info '.github/workflows/build-cpu.yml:73'
warn 'run this yourself (needs root or a system package manager): sudo apt-get install -y gcc-14 g++-14'
info '.github/workflows/build-cpu.yml:82'
warn 'run this yourself (needs root or a system package manager): choco install ninja'
info '.github/workflows/build-cpu.yml:189'
step '.github/workflows/build-cpu.yml:89' 'python3 -m pip install --upgrade pip setuptools'
step '.github/workflows/build-cpu.yml:89' 'pip3 install ./gguf-py'

bold "Build"
step '.github/workflows/build-cpu.yml:105' 'cmake -B build'
step '.github/workflows/build-cpu.yml:105' 'time cmake --build build --config Release -j $(nproc)'
step '.github/workflows/build-cpu.yml:195' 'cmake -S . -B build -G "Ninja Multi-Config" -D CMAKE_TOOLCHAIN_FILE=cmake/x64-windows-llvm.cmake -DGGML_NATIVE=OFF -DGGML_OPENMP_FETCH=ON -DLLAMA_BUILD_SERVER=ON -DGGML_RPC=ON -DBUILD_SHARED_LIBS=OFF | -G "Ninja Multi-Config" -D CMAKE_TOOLCHAIN_FILE=cmake/x64-windows-llvm.cmake -DGGML_NATIVE=OFF -DLLAMA_BUILD_SERVER=ON -DGGML_RPC=ON -DGGML_BACKEND_DL=ON -DGGML_CPU_ALL_VARIANTS=ON -DGGML_OPENMP=OFF -DGGML_BLAS=ON -DGGML_BLAS_VENDOR=OpenBLAS -DBLAS_INCLUDE_DIRS="$env:RUNNER_TEMP/openblas/include" -DBLAS_LIBRARIES="$env:RUNNER_TEMP/openblas/lib/openblas.lib" | -G "Ninja Multi-Config" -D CMAKE_TOOLCHAIN_FILE=cmake/arm64-windows-llvm.cmake -DGGML_NATIVE=OFF -DGGML_OPENMP_FETCH=ON -DLLAMA_BUILD_SERVER=ON `'
step '.github/workflows/build-cpu.yml:195' 'cmake --build build --config Release -j ${env:NUMBER_OF_PROCESSORS}'

if [ "$SKIP_TESTS" = 1 ]; then
  bold "Skipping tests (--skip-tests)"
else
  bold "Test"
  step '.github/workflows/build-cpu.yml:126' 'ctest -L main --verbose --timeout 900'
  step '.github/workflows/build-cpu.yml:210' 'ctest -L main -C Release --verbose --timeout 900'
fi

bold "Done"
info "Every command above came from .github/workflows/build-cpu.yml at 74a7c897f049."
