#!/usr/bin/env bash
#
# mastodon/mastodon -- setup derived from CI, not from prose.
#
# Generated by FACTCHECK from mastodon/mastodon at 0a32b4a83183
# Source of every command below: .github/workflows/test-ruby.yml
#
# These commands were read from a CI workflow. CI runs on a disposable
# machine with root and with its services already running; your machine
# is not that. Read this before you run it -- every line cites the file
# and line it came from, so it can be checked against the repo.
#
# Dropped on purpose: anything not literal in CI, anything that
# publishes, and anything needing sudo (printed instead, never run).
#
# Run this from the root of a clone of the repository above; the
# commands are the ones CI runs there, with its paths.
#
# One limit worth knowing: commands are taken individually from CI
# steps, so any `if` around them in the original workflow is not
# reproduced here. Read the cited lines if a step looks conditional.

set -euo pipefail

DRY_RUN=0
START_SERVICES=0
SKIP_TESTS=0

usage() {
  cat <<'EOF'
factcheck.sh -- reproduce this repo's CI setup locally

  --dry-run         print every command, run nothing
  --with-services   start the services CI declares, via docker
  --skip-tests      set up only; do not run the test suite
  -h, --help        this
EOF
}

while [ $# -gt 0 ]; do
  case "$1" in
    --dry-run) DRY_RUN=1 ;;
    --with-services) START_SERVICES=1 ;;
    --skip-tests) SKIP_TESTS=1 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "unknown option: $1" >&2; usage; exit 2 ;;
  esac
  shift
done

bold() { printf '\n\033[1m==> %s\033[0m\n' "$1"; }
info() { printf '    %s\n' "$1"; }
warn() { printf '    \033[33m!  %s\033[0m\n' "$1"; }

# Run one command, citing where it came from.
step() { # step <cite> <command>
  printf "    \033[2m%s\033[0m\n    $ %s\n" "$1" "$2"
  [ "$DRY_RUN" = 1 ] && return 0
  ( eval "$2" )
}

step_in() { # step_in <dir> <cite> <command>
  printf "    \033[2m%s (in %s)\033[0m\n    $ %s\n" "$2" "$1" "$3"
  [ "$DRY_RUN" = 1 ] && return 0
  ( cd "$1" && eval "$3" )
}

have() { command -v "$1" >/dev/null 2>&1; }

port_open() { # port_open <port>
  (exec 3<>"/dev/tcp/127.0.0.1/$1") >/dev/null 2>&1
}

bold "Where you are"
if [ -d .git ]; then
  origin="$(git config --get remote.origin.url 2>/dev/null || true)"
  case "$origin" in
    *mastodon/mastodon*) info "In a clone of mastodon/mastodon." ;;
    "") warn "This git repo has no origin; check you are in mastodon/mastodon." ;;
    *) warn "This looks like $origin, not mastodon/mastodon. The commands below assume the latter." ;;
  esac
else
  warn "Not inside a git repository. Run this from the root of a clone of mastodon/mastodon."
fi

bold "System packages CI's runner already had"
info "These are not installed by pip or npm. Install them yourself; this script will not run anything as root."
warn 'pg needs pg_config, from the PostgreSQL client library  <- Gemfile:13'
if command -v apt-get >/dev/null 2>&1; then
  info 'sudo apt-get install -y libpq-dev'
elif command -v brew >/dev/null 2>&1; then
  info 'brew install libpq'
elif command -v pacman >/dev/null 2>&1; then
  info 'sudo pacman -S --needed postgresql-libs'
elif command -v dnf >/dev/null 2>&1; then
  info 'sudo dnf install -y libpq-devel'
fi

bold "Checking what CI says this needs"
MISSING=0
if have node; then
  info "node: want 24.19, have $(node --version)"
else
  warn "node not installed -- CI uses 24.19 (.nvmrc:1)"
  MISSING=1
fi
if have ruby; then
  info "ruby: want 4.0.6, have $(ruby --version)"
else
  warn "ruby not installed -- CI uses 4.0.6 (.ruby-version:1)"
  MISSING=1
fi
info 'yarn 4.18.0 expected -- package.json:4'
if [ "$MISSING" = 1 ]; then
  warn "Install what is missing before continuing."
fi

bold "Environment CI sets"
export ALLOW_NOPAM='true'
info 'ALLOW_NOPAM=true  <- .github/workflows/test-ruby.yml:114'
export BUNDLE_WITH='pam_authentication test'
info 'BUNDLE_WITH=pam_authentication test  <- .github/workflows/test-ruby.yml:122'
info '  other jobs use: test'
export CAS_ENABLED='true'
info 'CAS_ENABLED=true  <- .github/workflows/test-ruby.yml:121'
export DB_HOST='localhost'
info 'DB_HOST=localhost  <- .github/workflows/test-ruby.yml:109'
export DB_PASS='postgres'
info 'DB_PASS=postgres  <- .github/workflows/test-ruby.yml:111'
export DB_USER='postgres'
info 'DB_USER=postgres  <- .github/workflows/test-ruby.yml:110'
export ES_ENABLED='true'
info 'ES_ENABLED=true  <- .github/workflows/test-ruby.yml:349'
export ES_HOST='localhost'
info 'ES_HOST=localhost  <- .github/workflows/test-ruby.yml:350'
export ES_PORT='9200'
info 'ES_PORT=9200  <- .github/workflows/test-ruby.yml:351'
export LOCAL_DOMAIN='localhost:3000'
info 'LOCAL_DOMAIN=localhost:3000  <- .github/workflows/test-ruby.yml:217'
export LOCAL_HTTPS='false'
info 'LOCAL_HTTPS=false  <- .github/workflows/test-ruby.yml:218'
export OIDC_ENABLED='true'
info 'OIDC_ENABLED=true  <- .github/workflows/test-ruby.yml:118'
export OIDC_SCOPE='read'
info 'OIDC_SCOPE=read  <- .github/workflows/test-ruby.yml:119'
export PAM_CONTROLLED_SERVICE='pam_test_controlled'
info 'PAM_CONTROLLED_SERVICE=pam_test_controlled  <- .github/workflows/test-ruby.yml:117'
export PAM_DEFAULT_SERVICE='pam_test'
info 'PAM_DEFAULT_SERVICE=pam_test  <- .github/workflows/test-ruby.yml:116'
export PAM_ENABLED='true'
info 'PAM_ENABLED=true  <- .github/workflows/test-ruby.yml:115'
export RAILS_ENV='test'
info 'RAILS_ENV=test  <- .github/workflows/test-ruby.yml:113'
export SAML_ENABLED='true'
info 'SAML_ENABLED=true  <- .github/workflows/test-ruby.yml:120'
export SECRET_KEY_BASE_DUMMY='1'
info 'SECRET_KEY_BASE_DUMMY=1  <- .github/workflows/test-ruby.yml:33'

bold "Services CI runs alongside the tests"
info 'postgres  postgres:14-alpine  <- .github/workflows/test-ruby.yml:86'
if port_open 5432; then
  info "postgres: something is listening on 5432"
elif [ "$START_SERVICES" = 1 ]; then
  if ! step '.github/workflows/test-ruby.yml:86' 'docker run -d --name factcheck-postgres -p 5432:5432 -e POSTGRES_PASSWORD=postgres -e POSTGRES_USER=postgres postgres:14-alpine'; then
    warn "could not start postgres. Start it yourself on port 5432 and re-run, or drop --with-services."
    exit 1
  fi
else
  warn "postgres: nothing on port 5432. Start it, or re-run with --with-services:"
  info 'docker run -d --name factcheck-postgres -p 5432:5432 -e POSTGRES_PASSWORD=postgres -e POSTGRES_USER=postgres postgres:14-alpine'
fi
info 'redis  redis:7-alpine  <- .github/workflows/test-ruby.yml:99'
if port_open 6379; then
  info "redis: something is listening on 6379"
elif [ "$START_SERVICES" = 1 ]; then
  if ! step '.github/workflows/test-ruby.yml:99' 'docker run -d --name factcheck-redis -p 6379:6379 redis:7-alpine'; then
    warn "could not start redis. Start it yourself on port 6379 and re-run, or drop --with-services."
    exit 1
  fi
else
  warn "redis: nothing on port 6379. Start it, or re-run with --with-services:"
  info 'docker run -d --name factcheck-redis -p 6379:6379 redis:7-alpine'
fi

bold "Setup"
step '.github/workflows/test-ruby.yml:62' 'bin/rails assets:precompile'
step '.github/workflows/test-ruby.yml:153' 'bin/rails db:setup'
step '.github/workflows/test-ruby.yml:251' './bin/rails db:create db:schema:load db:seed'

if [ "$SKIP_TESTS" = 1 ]; then
  bold "Skipping tests (--skip-tests)"
else
  bold "Test"
  step '.github/workflows/test-ruby.yml:169' 'bin/flatware rspec'
  step '.github/workflows/test-ruby.yml:262' 'yarn run playwright install --with-deps chromium'
  step '.github/workflows/test-ruby.yml:266' 'yarn run playwright install-deps chromium'
  step '.github/workflows/test-ruby.yml:268' 'bin/rspec spec/system --tag streaming --tag js'
  step '.github/workflows/test-ruby.yml:389' 'bin/rspec --tag search'
fi

bold "Done"
info "Every command above came from .github/workflows/test-ruby.yml at 0a32b4a83183."
