#!/usr/bin/env bash
#
# netbox-community/netbox -- setup derived from CI, not from prose.
#
# Generated by FACTCHECK from netbox-community/netbox at eaf30a6fb00e
# Source of every command below: .github/workflows/ci.yml
#
# These commands were read from a CI workflow. CI runs on a disposable
# machine with root and with its services already running; your machine
# is not that. Read this before you run it -- every line cites the file
# and line it came from, so it can be checked against the repo.
#
# Dropped on purpose: anything not literal in CI, anything that
# publishes, and anything needing sudo (printed instead, never run).
#
# One limit worth knowing: commands are taken individually from CI
# steps, so any `if` around them in the original workflow is not
# reproduced here. Read the cited lines if a step looks conditional.

set -euo pipefail

DRY_RUN=0
START_SERVICES=0
SKIP_TESTS=0

usage() {
  cat <<'EOF'
factcheck.sh -- reproduce this repo's CI setup locally

  --dry-run         print every command, run nothing
  --with-services   start the services CI declares, via docker
  --skip-tests      set up only; do not run the test suite
  -h, --help        this
EOF
}

while [ $# -gt 0 ]; do
  case "$1" in
    --dry-run) DRY_RUN=1 ;;
    --with-services) START_SERVICES=1 ;;
    --skip-tests) SKIP_TESTS=1 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "unknown option: $1" >&2; usage; exit 2 ;;
  esac
  shift
done

bold() { printf '\n\033[1m==> %s\033[0m\n' "$1"; }
info() { printf '    %s\n' "$1"; }
warn() { printf '    \033[33m!  %s\033[0m\n' "$1"; }

# Run one command, citing where it came from.
step() { # step <cite> <command>
  printf "    \033[2m%s\033[0m\n    $ %s\n" "$1" "$2"
  [ "$DRY_RUN" = 1 ] && return 0
  ( eval "$2" )
}

step_in() { # step_in <dir> <cite> <command>
  printf "    \033[2m%s (in %s)\033[0m\n    $ %s\n" "$2" "$1" "$3"
  [ "$DRY_RUN" = 1 ] && return 0
  ( cd "$1" && eval "$3" )
}

have() { command -v "$1" >/dev/null 2>&1; }

port_open() { # port_open <port>
  (exec 3<>"/dev/tcp/127.0.0.1/$1") >/dev/null 2>&1
}

bold "Checking what CI says this needs"
MISSING=0
if have node; then
  info "node: want 20, have $(node --version)"
else
  warn "node not installed -- CI uses 20 (.github/workflows/ci.yml:162)"
  MISSING=1
fi
if have python3; then
  info "python: want 3.12 | 3.13 | 3.14, have $(python3 --version)"
else
  warn "python not installed -- CI uses 3.12 | 3.13 | 3.14 (.github/workflows/ci.yml:118)"
  MISSING=1
fi
if [ "$MISSING" = 1 ]; then
  warn "Install what is missing before continuing."
fi

bold "Environment CI sets"
export NETBOX_CONFIGURATION='netbox.configuration_testing'
info 'NETBOX_CONFIGURATION=netbox.configuration_testing  <- .github/workflows/ci.yml:84'

bold "Services CI runs alongside the tests"
info 'postgres  postgres  <- .github/workflows/ci.yml:99'
if port_open 5432; then
  info "postgres: something is listening on 5432"
elif [ "$START_SERVICES" = 1 ]; then
  step '.github/workflows/ci.yml:99' 'docker run -d --name factcheck-postgres -p 5432:5432 -e POSTGRES_PASSWORD=postgres postgres'
else
  warn "postgres: nothing on port 5432. Start it, or re-run with --with-services:"
  info 'docker run -d --name factcheck-postgres -p 5432:5432 -e POSTGRES_PASSWORD=postgres postgres'
fi
info 'redis  redis  <- .github/workflows/ci.yml:95'
if port_open 6379; then
  info "redis: something is listening on 6379"
elif [ "$START_SERVICES" = 1 ]; then
  step '.github/workflows/ci.yml:95' 'docker run -d --name factcheck-redis -p 6379:6379 redis'
else
  warn "redis: nothing on port 6379. Start it, or re-run with --with-services:"
  info 'docker run -d --name factcheck-redis -p 6379:6379 redis'
fi

bold "Install"
warn 'run this yourself (needs root or a system package manager): npm install -g yarn'
info '.github/workflows/ci.yml:165'
step '.github/workflows/ci.yml:122' 'python -m pip install --upgrade pip'
step '.github/workflows/ci.yml:122' 'pip install -r requirements.txt'
step '.github/workflows/ci.yml:122' 'pip install coverage tblib'

bold "Setup"
step '.github/workflows/ci.yml:127' 'python netbox/manage.py makemigrations --check'
step '.github/workflows/ci.yml:132' 'python netbox/manage.py collectstatic --no-input'

bold "Build"
step '.github/workflows/release.yml:91' 'python -m build'

if [ "$SKIP_TESTS" = 1 ]; then
  bold "Skipping tests (--skip-tests)"
else
  bold "Test"
  step '.github/workflows/ci.yml:136' 'python netbox/manage.py test netbox/ --parallel'
  step '.github/workflows/ci.yml:140' 'coverage run netbox/manage.py test netbox/ --parallel'
fi

bold "Done"
info "Every command above came from .github/workflows/ci.yml at eaf30a6fb00e."
