#!/usr/bin/env bash
#
# wagtail/wagtail -- setup derived from CI, not from prose.
#
# Generated by FACTCHECK from wagtail/wagtail at bddc5eaf2e77
# Source of every command below: .github/workflows/test.yml
#
# These commands were read from a CI workflow. CI runs on a disposable
# machine with root and with its services already running; your machine
# is not that. Read this before you run it -- every line cites the file
# and line it came from, so it can be checked against the repo.
#
# Dropped on purpose: anything not literal in CI, anything that
# publishes, and anything needing sudo (printed instead, never run).
#
# Run this from the root of a clone of the repository above; the
# commands are the ones CI runs there, with its paths.
#
# One limit worth knowing: commands are taken individually from CI
# steps, so any `if` around them in the original workflow is not
# reproduced here. Read the cited lines if a step looks conditional.

set -euo pipefail

DRY_RUN=0
START_SERVICES=0
SKIP_TESTS=0

usage() {
  cat <<'EOF'
factcheck.sh -- reproduce this repo's CI setup locally

  --dry-run         print every command, run nothing
  --with-services   start the services CI declares, via docker
  --skip-tests      set up only; do not run the test suite
  -h, --help        this
EOF
}

while [ $# -gt 0 ]; do
  case "$1" in
    --dry-run) DRY_RUN=1 ;;
    --with-services) START_SERVICES=1 ;;
    --skip-tests) SKIP_TESTS=1 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "unknown option: $1" >&2; usage; exit 2 ;;
  esac
  shift
done

bold() { printf '\n\033[1m==> %s\033[0m\n' "$1"; }
info() { printf '    %s\n' "$1"; }
warn() { printf '    \033[33m!  %s\033[0m\n' "$1"; }

# Run one command, citing where it came from.
step() { # step <cite> <command>
  printf "    \033[2m%s\033[0m\n    $ %s\n" "$1" "$2"
  [ "$DRY_RUN" = 1 ] && return 0
  ( eval "$2" )
}

step_in() { # step_in <dir> <cite> <command>
  printf "    \033[2m%s (in %s)\033[0m\n    $ %s\n" "$2" "$1" "$3"
  [ "$DRY_RUN" = 1 ] && return 0
  ( cd "$1" && eval "$3" )
}

have() { command -v "$1" >/dev/null 2>&1; }

port_open() { # port_open <port>
  (exec 3<>"/dev/tcp/127.0.0.1/$1") >/dev/null 2>&1
}

bold "Where you are"
if [ -d .git ]; then
  origin="$(git config --get remote.origin.url 2>/dev/null || true)"
  case "$origin" in
    *wagtail/wagtail*) info "In a clone of wagtail/wagtail." ;;
    "") warn "This git repo has no origin; check you are in wagtail/wagtail." ;;
    *) warn "This looks like $origin, not wagtail/wagtail. The commands below assume the latter." ;;
  esac
else
  warn "Not inside a git repository. Run this from the root of a clone of wagtail/wagtail."
fi

bold "Checking what CI says this needs"
MISSING=0
if have node; then
  info "node: want 24, have $(node --version)"
else
  warn "node not installed -- CI uses 24 (.nvmrc:1)"
  MISSING=1
fi
if have python3; then
  info "python: want 3.13 | 3.11 | 3.14 | 3.12, have $(python3 --version)"
else
  warn "python not installed -- CI uses 3.13 | 3.11 | 3.14 | 3.12 (.github/workflows/test.yml:70)"
  MISSING=1
fi
if [ "$MISSING" = 1 ]; then
  warn "Install what is missing before continuing."
fi

bold "Environment CI sets"
export DATABASE_ENGINE='django.db.backends.sqlite3'
info 'DATABASE_ENGINE=django.db.backends.sqlite3  <- .github/workflows/test.yml:83'
info '  other jobs use: django.db.backends.postgresql, django.db.backends.mysql'
export DATABASE_HOST='localhost'
info 'DATABASE_HOST=localhost  <- .github/workflows/test.yml:163'
info '  other jobs use: 127.0.0.1'
export DATABASE_PASSWORD='postgres'
info 'DATABASE_PASSWORD=postgres  <- .github/workflows/test.yml:165'
info '  other jobs use: root'
export DATABASE_USER='postgres'
info 'DATABASE_USER=postgres  <- .github/workflows/test.yml:164'
info '  other jobs use: root'
export PYTHONWARNINGS='error'
info 'PYTHONWARNINGS=error  <- .github/workflows/test.yml:178'

bold "Services CI runs alongside the tests"
info 'elasticsearch  docker.elastic.co/elasticsearch/elasticsearch:8.11.2 | docker.elastic.co/elasticsearch/elasticsearch:7.17.13  <- .github/workflows/test.yml:278'
if port_open 9200; then
  info "elasticsearch: something is listening on 9200"
elif [ "$START_SERVICES" = 1 ]; then
  step '.github/workflows/test.yml:278' 'docker run -d --name factcheck-elasticsearch -p 9200:9200 docker.elastic.co/elasticsearch/elasticsearch:8.11.2'
else
  warn "elasticsearch: nothing on port 9200. Start it, or re-run with --with-services:"
  info 'docker run -d --name factcheck-elasticsearch -p 9200:9200 docker.elastic.co/elasticsearch/elasticsearch:8.11.2'
fi
info 'postgres  postgres:latest  <- .github/workflows/test.yml:335'
if port_open 5432; then
  info "postgres: something is listening on 5432"
elif [ "$START_SERVICES" = 1 ]; then
  step '.github/workflows/test.yml:335' 'docker run -d --name factcheck-postgres -p 5432:5432 -e POSTGRES_PASSWORD=postgres postgres:latest'
else
  warn "postgres: nothing on port 5432. Start it, or re-run with --with-services:"
  info 'docker run -d --name factcheck-postgres -p 5432:5432 -e POSTGRES_PASSWORD=postgres postgres:latest'
fi

bold "Install"
warn 'run this yourself (needs root or a system package manager): sudo apt-get install -y libpq-dev'
info '.github/workflows/test.yml:146'
step '.github/workflows/test.yml:75' 'uv sync --locked --extra testing --config-setting editable_mode=strict'
step '.github/workflows/test.yml:75' 'uv pip install "Django>=5.2,<5.3 | Django>=6.0,<6.1"'
step '.github/workflows/test.yml:152' 'uv pip install "psycopg2>=2.8.4 | psycopg>=3.1.8"'
step '.github/workflows/test.yml:152' 'uv pip install "Django>=5.2,<5.3 | Django>=6.1,<6.2 | git+https://github.com/django/django.git@stable/6.1.x#egg=Django | git+https://github.com/django/django.git@main#egg=Django"'
step '.github/workflows/test.yml:244' 'uv pip install mysqlclient'
step '.github/workflows/test.yml:244' 'uv pip install "Django>=5.2,<5.3 | Django>=6.0,<6.1 | Django>=6.1,<6.2"'
step '.github/workflows/test.yml:302' 'uv pip install "Django>=6.1,<6.2"'
step '.github/workflows/test.yml:302' 'uv pip install "elasticsearch>=8,<9"'
step '.github/workflows/test.yml:302' 'uv pip install certifi'
step '.github/workflows/test.yml:370' 'uv pip install "psycopg2>=2.6"'
step '.github/workflows/test.yml:370' 'uv pip install "Django>=5.2,<5.3"'
step '.github/workflows/test.yml:370' 'uv pip install "elasticsearch>=7,<8"'
step '.github/workflows/test.yml:426' 'uv pip install "opensearch-py>=2,<3"'
step '.github/workflows/test.yml:471' 'uv pip install --system coverage'

bold "Setup"
step '.github/workflows/test.yml:180' 'python manage.py makemigrations --check --dry-run'
step '.github/workflows/test.yml:180' 'python manage.py migrate'

bold "Build"
step 'package.json:146' 'npm run start'
step 'package.json:147' 'npm run build'
step 'package.json:165' 'npm run build-docs'
step 'package.json:166' 'npm run build-storybook'

if [ "$SKIP_TESTS" = 1 ]; then
  bold "Skipping tests (--skip-tests)"
else
  bold "Test"
  step 'package.json:159' 'npm run test'
  step 'package.json:160' 'npm run test:unit'
  step 'package.json:161' 'npm run test:unit:watch'
  step 'package.json:162' 'npm run test:unit:coverage'
  step 'package.json:163' 'npm run test:integration'
fi

bold "Done"
info "Every command above came from .github/workflows/test.yml at bddc5eaf2e77."
